use crate::api::*;
use crate::{ApiError, ClientConfig, HttpClient, QueryBuilder, RequestOptions};
use reqwest::Method;

pub mod summaries;
pub use summaries::SummariesClient2;
pub mod chunk;
pub use chunk::ChunkClient;
pub mod chunks;
pub use chunks::ChunksClient;
pub struct DocumentsClient {
    pub http_client: HttpClient,
    pub summaries: SummariesClient2,
    pub chunk: ChunkClient,
    pub chunks: ChunksClient,
}

impl DocumentsClient {
    pub fn new(config: ClientConfig) -> Result<Self, ApiError> {
        Ok(Self {
            http_client: HttpClient::new(config.clone())?,
            summaries: SummariesClient2::new(config.clone())?,
            chunk: ChunkClient::new(config.clone())?,
            chunks: ChunksClient::new(config.clone())?,
        })
    }

    /// Create a knowledge base document generated by scraping the given webpage.
    ///
    /// # Arguments
    ///
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .create_from_url(
    ///             &BodyCreateURLDocumentV1ConvaiKnowledgeBaseURLPost {
    ///                 url: "url".to_string(),
    ///                 name: None,
    ///                 parent_folder_id: None,
    ///                 enable_auto_sync: None,
    ///                 auto_remove: None,
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn create_from_url(
        &self,
        request: &BodyCreateUrlDocumentV1ConvaiKnowledgeBaseUrlPost,
        options: Option<RequestOptions>,
    ) -> Result<AddKnowledgeBaseResponseModel, ApiError> {
        self.http_client
            .execute_request(
                Method::POST,
                "v1/convai/knowledge-base/url",
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }

    /// Create a knowledge base document generated form the uploaded file.
    ///
    /// # Arguments
    ///
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .create_from_file(
    ///             &CreateFromFileRequest {
    ///                 file: b"test file content".to_vec(),
    ///                 name: None,
    ///                 parent_folder_id: None,
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn create_from_file(
        &self,
        request: &CreateFromFileRequest,
        options: Option<RequestOptions>,
    ) -> Result<AddKnowledgeBaseResponseModel, ApiError> {
        self.http_client
            .execute_multipart_request(
                Method::POST,
                "v1/convai/knowledge-base/file",
                request.clone().to_multipart(),
                None,
                options,
            )
            .await
    }

    /// Create a knowledge base document containing the provided text.
    ///
    /// # Arguments
    ///
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .create_from_text(
    ///             &BodyCreateTextDocumentV1ConvaiKnowledgeBaseTextPost {
    ///                 text: "text".to_string(),
    ///                 name: None,
    ///                 parent_folder_id: None,
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn create_from_text(
        &self,
        request: &BodyCreateTextDocumentV1ConvaiKnowledgeBaseTextPost,
        options: Option<RequestOptions>,
    ) -> Result<AddKnowledgeBaseResponseModel, ApiError> {
        self.http_client
            .execute_request(
                Method::POST,
                "v1/convai/knowledge-base/text",
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }

    /// Create a folder used for grouping documents together.
    ///
    /// # Arguments
    ///
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .create_folder(
    ///             &BodyCreateFolderV1ConvaiKnowledgeBaseFolderPost {
    ///                 name: "name".to_string(),
    ///                 parent_folder_id: None,
    ///                 enable_auto_sync: None,
    ///                 auto_remove: None,
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn create_folder(
        &self,
        request: &BodyCreateFolderV1ConvaiKnowledgeBaseFolderPost,
        options: Option<RequestOptions>,
    ) -> Result<AddKnowledgeBaseResponseModel, ApiError> {
        self.http_client
            .execute_request(
                Method::POST,
                "v1/convai/knowledge-base/folder",
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }

    /// Get details about a specific documentation making up the agent's knowledge base
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .get(
    ///             &"21m00Tcm4TlvDq8ikWAM".to_string(),
    ///             &ConversationalAiKnowledgeBaseDocumentsGetQueryRequest {
    ///                 agent_id: Some("agent_id".to_string()),
    ///                 ..Default::default()
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn get(
        &self,
        documentation_id: &str,
        request: &ConversationalAiKnowledgeBaseDocumentsGetQueryRequest,
        options: Option<RequestOptions>,
    ) -> Result<DocumentsGetResponse, ApiError> {
        self.http_client
            .execute_request(
                Method::GET,
                &format!("v1/convai/knowledge-base/{}", documentation_id),
                None,
                QueryBuilder::new()
                    .string("agent_id", request.agent_id.clone())
                    .build(),
                options,
            )
            .await
    }

    /// Delete a document or folder from the knowledge base.
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `force` - If set to true, the document or folder will be deleted regardless of whether it is used by any agents and it will be removed from the dependent agents. For non-empty folders, this will also delete all child documents and folders.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .delete(
    ///             &"21m00Tcm4TlvDq8ikWAM".to_string(),
    ///             &ConversationalAiKnowledgeBaseDocumentsDeleteQueryRequest {
    ///                 force: Some(true),
    ///                 ..Default::default()
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn delete(
        &self,
        documentation_id: &str,
        request: &ConversationalAiKnowledgeBaseDocumentsDeleteQueryRequest,
        options: Option<RequestOptions>,
    ) -> Result<serde_json::Value, ApiError> {
        self.http_client
            .execute_request(
                Method::DELETE,
                &format!("v1/convai/knowledge-base/{}", documentation_id),
                None,
                QueryBuilder::new()
                    .bool("force", request.force.clone())
                    .build(),
                options,
            )
            .await
    }

    /// Update the name and/or content of a document.
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .update(
    ///             &"21m00Tcm4TlvDq8ikWAM".to_string(),
    ///             &BodyUpdateDocumentV1ConvaiKnowledgeBaseDocumentationIDPatch {
    ///                 ..Default::default()
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn update(
        &self,
        documentation_id: &str,
        request: &BodyUpdateDocumentV1ConvaiKnowledgeBaseDocumentationIdPatch,
        options: Option<RequestOptions>,
    ) -> Result<DocumentsUpdateResponse, ApiError> {
        self.http_client
            .execute_request(
                Method::PATCH,
                &format!("v1/convai/knowledge-base/{}", documentation_id),
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }

    /// Get a list of agents depending on this knowledge base document
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `dependent_type` - Type of dependent agents to return.
    /// * `page_size` - How many documents to return at maximum. Can not exceed 100, defaults to 30.
    /// * `cursor` - Used for fetching next page. Cursor is returned in the response.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .get_agents(
    ///             &"21m00Tcm4TlvDq8ikWAM".to_string(),
    ///             &GetAgentsQueryRequest {
    ///                 dependent_type: Some(KnowledgeBaseDependentType::Direct),
    ///                 page_size: Some(1),
    ///                 cursor: Some("cursor".to_string()),
    ///                 ..Default::default()
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn get_agents(
        &self,
        documentation_id: &str,
        request: &GetAgentsQueryRequest,
        options: Option<RequestOptions>,
    ) -> Result<GetKnowledgeBaseDependentAgentsResponseModel, ApiError> {
        self.http_client
            .execute_request(
                Method::GET,
                &format!(
                    "v1/convai/knowledge-base/{}/dependent-agents",
                    documentation_id
                ),
                None,
                QueryBuilder::new()
                    .serialize("dependent_type", request.dependent_type.clone())
                    .int("page_size", request.page_size.clone())
                    .string("cursor", request.cursor.clone())
                    .build(),
                options,
            )
            .await
    }

    /// Get the entire content of a document from the knowledge base
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// Text response
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .get_content(&"documentation_id".to_string(), None)
    ///         .await;
    /// }
    /// ```
    pub async fn get_content(
        &self,
        documentation_id: &str,
        options: Option<RequestOptions>,
    ) -> Result<String, ApiError> {
        self.http_client
            .execute_request(
                Method::GET,
                &format!("v1/convai/knowledge-base/{}/content", documentation_id),
                None,
                None,
                options,
            )
            .await
    }

    /// Get a signed URL to download the original source file of a file-type document from the knowledge base
    ///
    /// # Arguments
    ///
    /// * `documentation_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// JSON response from the API
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .get_source_file_url(&"21m00Tcm4TlvDq8ikWAM".to_string(), None)
    ///         .await;
    /// }
    /// ```
    pub async fn get_source_file_url(
        &self,
        documentation_id: &str,
        options: Option<RequestOptions>,
    ) -> Result<KnowledgeBaseSourceFileUrlResponseModel, ApiError> {
        self.http_client
            .execute_request(
                Method::GET,
                &format!(
                    "v1/convai/knowledge-base/{}/source-file-url",
                    documentation_id
                ),
                None,
                None,
                options,
            )
            .await
    }

    /// Moves the entity from one folder to another.
    ///
    /// # Arguments
    ///
    /// * `document_id` - The id of a document from the knowledge base. This is returned on document addition.
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// Empty response
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .move_(
    ///             &"21m00Tcm4TlvDq8ikWAM".to_string(),
    ///             &BodyMoveEntityToFolderV1ConvaiKnowledgeBaseDocumentIDMovePost {
    ///                 ..Default::default()
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn move_(
        &self,
        document_id: &str,
        request: &BodyMoveEntityToFolderV1ConvaiKnowledgeBaseDocumentIdMovePost,
        options: Option<RequestOptions>,
    ) -> Result<(), ApiError> {
        self.http_client
            .execute_request(
                Method::POST,
                &format!("v1/convai/knowledge-base/{}/move", document_id),
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }

    /// Moves multiple entities from one folder to another.
    ///
    /// # Arguments
    ///
    /// * `options` - Additional request options such as headers, timeout, etc.
    ///
    /// # Returns
    ///
    /// Empty response
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use elevenlabs_sdk::prelude::*;
    ///
    /// #[tokio::main]
    /// async fn main() {
    ///     let config = ClientConfig {
    ///         ..Default::default()
    ///     };
    ///     let client = ElevenlabsClient::new(config).expect("Failed to build client");
    ///     client
    ///         .conversational_ai
    ///         .knowledge_base
    ///         .documents
    ///         .bulk_move(
    ///             &BodyBulkMoveEntitiesToFolderV1ConvaiKnowledgeBaseBulkMovePost {
    ///                 document_ids: vec![
    ///                     "21m00Tcm4TlvDq8ikWAM".to_string(),
    ///                     "31m00Tcm4TlvDq8ikWBM".to_string(),
    ///                 ],
    ///                 move_to: None,
    ///             },
    ///             None,
    ///         )
    ///         .await;
    /// }
    /// ```
    pub async fn bulk_move(
        &self,
        request: &BodyBulkMoveEntitiesToFolderV1ConvaiKnowledgeBaseBulkMovePost,
        options: Option<RequestOptions>,
    ) -> Result<(), ApiError> {
        self.http_client
            .execute_request(
                Method::POST,
                "v1/convai/knowledge-base/bulk-move",
                Some(serde_json::to_value(request).map_err(ApiError::Serialization)?),
                None,
                options,
            )
            .await
    }
}
