pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

/// Entity types for the API configuration.
/// 
/// This enum contains all valid entity type configurations that users can specify:
/// - Parent types (e.g., "name", "financial_id") that expand to all subtypes
/// - Specific subtypes using dot notation (e.g., "name.full_name")
/// - Standalone terminal types (e.g., "email_address")
/// 
/// When converted for service use, parent types expand to all their terminal subtypes.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ConfigEntityType {
    Name,
    NameNameGiven,
    NameNameFamily,
    NameNameOther,
    EmailAddress,
    ContactNumber,
    Dob,
    Age,
    ReligiousBelief,
    PoliticalOpinion,
    SexualOrientation,
    EthnicityRace,
    MaritalStatus,
    Occupation,
    PhysicalAttribute,
    Language,
    Username,
    Password,
    Url,
    Organization,
    FinancialId,
    FinancialIdPaymentCard,
    FinancialIdPaymentCardPaymentCardNumber,
    FinancialIdPaymentCardPaymentCardExpirationDate,
    FinancialIdPaymentCardPaymentCardCvv,
    FinancialIdBankAccount,
    FinancialIdBankAccountBankAccountNumber,
    FinancialIdBankAccountBankRoutingNumber,
    FinancialIdBankAccountSwiftBicCode,
    FinancialIdFinancialIdOther,
    Location,
    LocationLocationAddress,
    LocationLocationCity,
    LocationLocationPostalCode,
    LocationLocationCoordinate,
    LocationLocationState,
    LocationLocationCountry,
    LocationLocationOther,
    Date,
    DateInterval,
    UniqueId,
    UniqueIdGovernmentIssuedId,
    UniqueIdAccountNumber,
    UniqueIdVehicleId,
    UniqueIdHealthcareNumber,
    UniqueIdHealthcareNumberMedicalRecordNumber,
    UniqueIdHealthcareNumberHealthPlanBeneficiaryNumber,
    UniqueIdDeviceId,
    UniqueIdUniqueIdOther,
    Medical,
    MedicalMedicalCondition,
    MedicalMedication,
    MedicalMedicalProcedure,
    MedicalMedicalMeasurement,
    MedicalMedicalOther,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for ConfigEntityType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Name => serializer.serialize_str("name"),
            Self::NameNameGiven => serializer.serialize_str("name.name_given"),
            Self::NameNameFamily => serializer.serialize_str("name.name_family"),
            Self::NameNameOther => serializer.serialize_str("name.name_other"),
            Self::EmailAddress => serializer.serialize_str("email_address"),
            Self::ContactNumber => serializer.serialize_str("contact_number"),
            Self::Dob => serializer.serialize_str("dob"),
            Self::Age => serializer.serialize_str("age"),
            Self::ReligiousBelief => serializer.serialize_str("religious_belief"),
            Self::PoliticalOpinion => serializer.serialize_str("political_opinion"),
            Self::SexualOrientation => serializer.serialize_str("sexual_orientation"),
            Self::EthnicityRace => serializer.serialize_str("ethnicity_race"),
            Self::MaritalStatus => serializer.serialize_str("marital_status"),
            Self::Occupation => serializer.serialize_str("occupation"),
            Self::PhysicalAttribute => serializer.serialize_str("physical_attribute"),
            Self::Language => serializer.serialize_str("language"),
            Self::Username => serializer.serialize_str("username"),
            Self::Password => serializer.serialize_str("password"),
            Self::Url => serializer.serialize_str("url"),
            Self::Organization => serializer.serialize_str("organization"),
            Self::FinancialId => serializer.serialize_str("financial_id"),
            Self::FinancialIdPaymentCard => serializer.serialize_str("financial_id.payment_card"),
            Self::FinancialIdPaymentCardPaymentCardNumber => serializer.serialize_str("financial_id.payment_card.payment_card_number"),
            Self::FinancialIdPaymentCardPaymentCardExpirationDate => serializer.serialize_str("financial_id.payment_card.payment_card_expiration_date"),
            Self::FinancialIdPaymentCardPaymentCardCvv => serializer.serialize_str("financial_id.payment_card.payment_card_cvv"),
            Self::FinancialIdBankAccount => serializer.serialize_str("financial_id.bank_account"),
            Self::FinancialIdBankAccountBankAccountNumber => serializer.serialize_str("financial_id.bank_account.bank_account_number"),
            Self::FinancialIdBankAccountBankRoutingNumber => serializer.serialize_str("financial_id.bank_account.bank_routing_number"),
            Self::FinancialIdBankAccountSwiftBicCode => serializer.serialize_str("financial_id.bank_account.swift_bic_code"),
            Self::FinancialIdFinancialIdOther => serializer.serialize_str("financial_id.financial_id_other"),
            Self::Location => serializer.serialize_str("location"),
            Self::LocationLocationAddress => serializer.serialize_str("location.location_address"),
            Self::LocationLocationCity => serializer.serialize_str("location.location_city"),
            Self::LocationLocationPostalCode => serializer.serialize_str("location.location_postal_code"),
            Self::LocationLocationCoordinate => serializer.serialize_str("location.location_coordinate"),
            Self::LocationLocationState => serializer.serialize_str("location.location_state"),
            Self::LocationLocationCountry => serializer.serialize_str("location.location_country"),
            Self::LocationLocationOther => serializer.serialize_str("location.location_other"),
            Self::Date => serializer.serialize_str("date"),
            Self::DateInterval => serializer.serialize_str("date_interval"),
            Self::UniqueId => serializer.serialize_str("unique_id"),
            Self::UniqueIdGovernmentIssuedId => serializer.serialize_str("unique_id.government_issued_id"),
            Self::UniqueIdAccountNumber => serializer.serialize_str("unique_id.account_number"),
            Self::UniqueIdVehicleId => serializer.serialize_str("unique_id.vehicle_id"),
            Self::UniqueIdHealthcareNumber => serializer.serialize_str("unique_id.healthcare_number"),
            Self::UniqueIdHealthcareNumberMedicalRecordNumber => serializer.serialize_str("unique_id.healthcare_number.medical_record_number"),
            Self::UniqueIdHealthcareNumberHealthPlanBeneficiaryNumber => serializer.serialize_str("unique_id.healthcare_number.health_plan_beneficiary_number"),
            Self::UniqueIdDeviceId => serializer.serialize_str("unique_id.device_id"),
            Self::UniqueIdUniqueIdOther => serializer.serialize_str("unique_id.unique_id_other"),
            Self::Medical => serializer.serialize_str("medical"),
            Self::MedicalMedicalCondition => serializer.serialize_str("medical.medical_condition"),
            Self::MedicalMedication => serializer.serialize_str("medical.medication"),
            Self::MedicalMedicalProcedure => serializer.serialize_str("medical.medical_procedure"),
            Self::MedicalMedicalMeasurement => serializer.serialize_str("medical.medical_measurement"),
            Self::MedicalMedicalOther => serializer.serialize_str("medical.medical_other"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for ConfigEntityType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "name" => Ok(Self::Name),
            "name.name_given" => Ok(Self::NameNameGiven),
            "name.name_family" => Ok(Self::NameNameFamily),
            "name.name_other" => Ok(Self::NameNameOther),
            "email_address" => Ok(Self::EmailAddress),
            "contact_number" => Ok(Self::ContactNumber),
            "dob" => Ok(Self::Dob),
            "age" => Ok(Self::Age),
            "religious_belief" => Ok(Self::ReligiousBelief),
            "political_opinion" => Ok(Self::PoliticalOpinion),
            "sexual_orientation" => Ok(Self::SexualOrientation),
            "ethnicity_race" => Ok(Self::EthnicityRace),
            "marital_status" => Ok(Self::MaritalStatus),
            "occupation" => Ok(Self::Occupation),
            "physical_attribute" => Ok(Self::PhysicalAttribute),
            "language" => Ok(Self::Language),
            "username" => Ok(Self::Username),
            "password" => Ok(Self::Password),
            "url" => Ok(Self::Url),
            "organization" => Ok(Self::Organization),
            "financial_id" => Ok(Self::FinancialId),
            "financial_id.payment_card" => Ok(Self::FinancialIdPaymentCard),
            "financial_id.payment_card.payment_card_number" => Ok(Self::FinancialIdPaymentCardPaymentCardNumber),
            "financial_id.payment_card.payment_card_expiration_date" => Ok(Self::FinancialIdPaymentCardPaymentCardExpirationDate),
            "financial_id.payment_card.payment_card_cvv" => Ok(Self::FinancialIdPaymentCardPaymentCardCvv),
            "financial_id.bank_account" => Ok(Self::FinancialIdBankAccount),
            "financial_id.bank_account.bank_account_number" => Ok(Self::FinancialIdBankAccountBankAccountNumber),
            "financial_id.bank_account.bank_routing_number" => Ok(Self::FinancialIdBankAccountBankRoutingNumber),
            "financial_id.bank_account.swift_bic_code" => Ok(Self::FinancialIdBankAccountSwiftBicCode),
            "financial_id.financial_id_other" => Ok(Self::FinancialIdFinancialIdOther),
            "location" => Ok(Self::Location),
            "location.location_address" => Ok(Self::LocationLocationAddress),
            "location.location_city" => Ok(Self::LocationLocationCity),
            "location.location_postal_code" => Ok(Self::LocationLocationPostalCode),
            "location.location_coordinate" => Ok(Self::LocationLocationCoordinate),
            "location.location_state" => Ok(Self::LocationLocationState),
            "location.location_country" => Ok(Self::LocationLocationCountry),
            "location.location_other" => Ok(Self::LocationLocationOther),
            "date" => Ok(Self::Date),
            "date_interval" => Ok(Self::DateInterval),
            "unique_id" => Ok(Self::UniqueId),
            "unique_id.government_issued_id" => Ok(Self::UniqueIdGovernmentIssuedId),
            "unique_id.account_number" => Ok(Self::UniqueIdAccountNumber),
            "unique_id.vehicle_id" => Ok(Self::UniqueIdVehicleId),
            "unique_id.healthcare_number" => Ok(Self::UniqueIdHealthcareNumber),
            "unique_id.healthcare_number.medical_record_number" => Ok(Self::UniqueIdHealthcareNumberMedicalRecordNumber),
            "unique_id.healthcare_number.health_plan_beneficiary_number" => Ok(Self::UniqueIdHealthcareNumberHealthPlanBeneficiaryNumber),
            "unique_id.device_id" => Ok(Self::UniqueIdDeviceId),
            "unique_id.unique_id_other" => Ok(Self::UniqueIdUniqueIdOther),
            "medical" => Ok(Self::Medical),
            "medical.medical_condition" => Ok(Self::MedicalMedicalCondition),
            "medical.medication" => Ok(Self::MedicalMedication),
            "medical.medical_procedure" => Ok(Self::MedicalMedicalProcedure),
            "medical.medical_measurement" => Ok(Self::MedicalMedicalMeasurement),
            "medical.medical_other" => Ok(Self::MedicalMedicalOther),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for ConfigEntityType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Name => write!(f, "name"),
            Self::NameNameGiven => write!(f, "name.name_given"),
            Self::NameNameFamily => write!(f, "name.name_family"),
            Self::NameNameOther => write!(f, "name.name_other"),
            Self::EmailAddress => write!(f, "email_address"),
            Self::ContactNumber => write!(f, "contact_number"),
            Self::Dob => write!(f, "dob"),
            Self::Age => write!(f, "age"),
            Self::ReligiousBelief => write!(f, "religious_belief"),
            Self::PoliticalOpinion => write!(f, "political_opinion"),
            Self::SexualOrientation => write!(f, "sexual_orientation"),
            Self::EthnicityRace => write!(f, "ethnicity_race"),
            Self::MaritalStatus => write!(f, "marital_status"),
            Self::Occupation => write!(f, "occupation"),
            Self::PhysicalAttribute => write!(f, "physical_attribute"),
            Self::Language => write!(f, "language"),
            Self::Username => write!(f, "username"),
            Self::Password => write!(f, "password"),
            Self::Url => write!(f, "url"),
            Self::Organization => write!(f, "organization"),
            Self::FinancialId => write!(f, "financial_id"),
            Self::FinancialIdPaymentCard => write!(f, "financial_id.payment_card"),
            Self::FinancialIdPaymentCardPaymentCardNumber => write!(f, "financial_id.payment_card.payment_card_number"),
            Self::FinancialIdPaymentCardPaymentCardExpirationDate => write!(f, "financial_id.payment_card.payment_card_expiration_date"),
            Self::FinancialIdPaymentCardPaymentCardCvv => write!(f, "financial_id.payment_card.payment_card_cvv"),
            Self::FinancialIdBankAccount => write!(f, "financial_id.bank_account"),
            Self::FinancialIdBankAccountBankAccountNumber => write!(f, "financial_id.bank_account.bank_account_number"),
            Self::FinancialIdBankAccountBankRoutingNumber => write!(f, "financial_id.bank_account.bank_routing_number"),
            Self::FinancialIdBankAccountSwiftBicCode => write!(f, "financial_id.bank_account.swift_bic_code"),
            Self::FinancialIdFinancialIdOther => write!(f, "financial_id.financial_id_other"),
            Self::Location => write!(f, "location"),
            Self::LocationLocationAddress => write!(f, "location.location_address"),
            Self::LocationLocationCity => write!(f, "location.location_city"),
            Self::LocationLocationPostalCode => write!(f, "location.location_postal_code"),
            Self::LocationLocationCoordinate => write!(f, "location.location_coordinate"),
            Self::LocationLocationState => write!(f, "location.location_state"),
            Self::LocationLocationCountry => write!(f, "location.location_country"),
            Self::LocationLocationOther => write!(f, "location.location_other"),
            Self::Date => write!(f, "date"),
            Self::DateInterval => write!(f, "date_interval"),
            Self::UniqueId => write!(f, "unique_id"),
            Self::UniqueIdGovernmentIssuedId => write!(f, "unique_id.government_issued_id"),
            Self::UniqueIdAccountNumber => write!(f, "unique_id.account_number"),
            Self::UniqueIdVehicleId => write!(f, "unique_id.vehicle_id"),
            Self::UniqueIdHealthcareNumber => write!(f, "unique_id.healthcare_number"),
            Self::UniqueIdHealthcareNumberMedicalRecordNumber => write!(f, "unique_id.healthcare_number.medical_record_number"),
            Self::UniqueIdHealthcareNumberHealthPlanBeneficiaryNumber => write!(f, "unique_id.healthcare_number.health_plan_beneficiary_number"),
            Self::UniqueIdDeviceId => write!(f, "unique_id.device_id"),
            Self::UniqueIdUniqueIdOther => write!(f, "unique_id.unique_id_other"),
            Self::Medical => write!(f, "medical"),
            Self::MedicalMedicalCondition => write!(f, "medical.medical_condition"),
            Self::MedicalMedication => write!(f, "medical.medication"),
            Self::MedicalMedicalProcedure => write!(f, "medical.medical_procedure"),
            Self::MedicalMedicalMeasurement => write!(f, "medical.medical_measurement"),
            Self::MedicalMedicalOther => write!(f, "medical.medical_other"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
