pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DirectPublishingReadResponseModelGenreItem {
    Fantasy,
    Romance,
    ScienceFiction,
    MysteryAndThriller,
    ActionAndAdventure,
    Dystopia,
    BusinessAndEconomics,
    Technology,
    ChristianInspirational,
    Horror,
    BiographyAndMemoir,
    EducationAndLearning,
    History,
    ChildrensLiterature,
    YoungAdult,
    FairyTalesAndFolklore,
    FanFiction,
    GeneralFiction,
    HealthAndWellness,
    HistoricalFiction,
    Humor,
    LiteraryClassics,
    Philosophy,
    Poetry,
    PoliticsAndGovernment,
    Psychology,
    ScienceAndNature,
    SelfHelp,
    SpiritualityAndReligion,
    Travel,
    TrueCrime,
    Other,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for DirectPublishingReadResponseModelGenreItem {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Fantasy => serializer.serialize_str("Fantasy"),
            Self::Romance => serializer.serialize_str("Romance"),
            Self::ScienceFiction => serializer.serialize_str("Science Fiction"),
            Self::MysteryAndThriller => serializer.serialize_str("Mystery and Thriller"),
            Self::ActionAndAdventure => serializer.serialize_str("Action and Adventure"),
            Self::Dystopia => serializer.serialize_str("Dystopia"),
            Self::BusinessAndEconomics => serializer.serialize_str("Business and Economics"),
            Self::Technology => serializer.serialize_str("Technology"),
            Self::ChristianInspirational => serializer.serialize_str("Christian & Inspirational"),
            Self::Horror => serializer.serialize_str("Horror"),
            Self::BiographyAndMemoir => serializer.serialize_str("Biography and Memoir"),
            Self::EducationAndLearning => serializer.serialize_str("Education and Learning"),
            Self::History => serializer.serialize_str("History"),
            Self::ChildrensLiterature => serializer.serialize_str("Children's Literature"),
            Self::YoungAdult => serializer.serialize_str("Young Adult"),
            Self::FairyTalesAndFolklore => serializer.serialize_str("Fairy Tales and Folklore"),
            Self::FanFiction => serializer.serialize_str("Fan Fiction"),
            Self::GeneralFiction => serializer.serialize_str("General Fiction"),
            Self::HealthAndWellness => serializer.serialize_str("Health and Wellness"),
            Self::HistoricalFiction => serializer.serialize_str("Historical Fiction"),
            Self::Humor => serializer.serialize_str("Humor"),
            Self::LiteraryClassics => serializer.serialize_str("Literary Classics"),
            Self::Philosophy => serializer.serialize_str("Philosophy"),
            Self::Poetry => serializer.serialize_str("Poetry"),
            Self::PoliticsAndGovernment => serializer.serialize_str("Politics and Government"),
            Self::Psychology => serializer.serialize_str("Psychology"),
            Self::ScienceAndNature => serializer.serialize_str("Science and Nature"),
            Self::SelfHelp => serializer.serialize_str("Self-Help"),
            Self::SpiritualityAndReligion => serializer.serialize_str("Spirituality and Religion"),
            Self::Travel => serializer.serialize_str("Travel"),
            Self::TrueCrime => serializer.serialize_str("True Crime"),
            Self::Other => serializer.serialize_str("Other"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for DirectPublishingReadResponseModelGenreItem {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "Fantasy" => Ok(Self::Fantasy),
            "Romance" => Ok(Self::Romance),
            "Science Fiction" => Ok(Self::ScienceFiction),
            "Mystery and Thriller" => Ok(Self::MysteryAndThriller),
            "Action and Adventure" => Ok(Self::ActionAndAdventure),
            "Dystopia" => Ok(Self::Dystopia),
            "Business and Economics" => Ok(Self::BusinessAndEconomics),
            "Technology" => Ok(Self::Technology),
            "Christian & Inspirational" => Ok(Self::ChristianInspirational),
            "Horror" => Ok(Self::Horror),
            "Biography and Memoir" => Ok(Self::BiographyAndMemoir),
            "Education and Learning" => Ok(Self::EducationAndLearning),
            "History" => Ok(Self::History),
            "Children's Literature" => Ok(Self::ChildrensLiterature),
            "Young Adult" => Ok(Self::YoungAdult),
            "Fairy Tales and Folklore" => Ok(Self::FairyTalesAndFolklore),
            "Fan Fiction" => Ok(Self::FanFiction),
            "General Fiction" => Ok(Self::GeneralFiction),
            "Health and Wellness" => Ok(Self::HealthAndWellness),
            "Historical Fiction" => Ok(Self::HistoricalFiction),
            "Humor" => Ok(Self::Humor),
            "Literary Classics" => Ok(Self::LiteraryClassics),
            "Philosophy" => Ok(Self::Philosophy),
            "Poetry" => Ok(Self::Poetry),
            "Politics and Government" => Ok(Self::PoliticsAndGovernment),
            "Psychology" => Ok(Self::Psychology),
            "Science and Nature" => Ok(Self::ScienceAndNature),
            "Self-Help" => Ok(Self::SelfHelp),
            "Spirituality and Religion" => Ok(Self::SpiritualityAndReligion),
            "Travel" => Ok(Self::Travel),
            "True Crime" => Ok(Self::TrueCrime),
            "Other" => Ok(Self::Other),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for DirectPublishingReadResponseModelGenreItem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Fantasy => write!(f, "Fantasy"),
            Self::Romance => write!(f, "Romance"),
            Self::ScienceFiction => write!(f, "Science Fiction"),
            Self::MysteryAndThriller => write!(f, "Mystery and Thriller"),
            Self::ActionAndAdventure => write!(f, "Action and Adventure"),
            Self::Dystopia => write!(f, "Dystopia"),
            Self::BusinessAndEconomics => write!(f, "Business and Economics"),
            Self::Technology => write!(f, "Technology"),
            Self::ChristianInspirational => write!(f, "Christian & Inspirational"),
            Self::Horror => write!(f, "Horror"),
            Self::BiographyAndMemoir => write!(f, "Biography and Memoir"),
            Self::EducationAndLearning => write!(f, "Education and Learning"),
            Self::History => write!(f, "History"),
            Self::ChildrensLiterature => write!(f, "Children's Literature"),
            Self::YoungAdult => write!(f, "Young Adult"),
            Self::FairyTalesAndFolklore => write!(f, "Fairy Tales and Folklore"),
            Self::FanFiction => write!(f, "Fan Fiction"),
            Self::GeneralFiction => write!(f, "General Fiction"),
            Self::HealthAndWellness => write!(f, "Health and Wellness"),
            Self::HistoricalFiction => write!(f, "Historical Fiction"),
            Self::Humor => write!(f, "Humor"),
            Self::LiteraryClassics => write!(f, "Literary Classics"),
            Self::Philosophy => write!(f, "Philosophy"),
            Self::Poetry => write!(f, "Poetry"),
            Self::PoliticsAndGovernment => write!(f, "Politics and Government"),
            Self::Psychology => write!(f, "Psychology"),
            Self::ScienceAndNature => write!(f, "Science and Nature"),
            Self::SelfHelp => write!(f, "Self-Help"),
            Self::SpiritualityAndReligion => write!(f, "Spirituality and Religion"),
            Self::Travel => write!(f, "Travel"),
            Self::TrueCrime => write!(f, "True Crime"),
            Self::Other => write!(f, "Other"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
