pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PermissionType {
    TextToSpeech,
    SpeechToSpeech,
    SpeechToText,
    ModelsRead,
    ModelsWrite,
    VoicesRead,
    VoicesWrite,
    SpeechHistoryRead,
    SpeechHistoryWrite,
    SoundGeneration,
    AudioIsolation,
    VoiceGeneration,
    DubbingRead,
    DubbingWrite,
    PronunciationDictionariesRead,
    PronunciationDictionariesWrite,
    UserRead,
    UserWrite,
    ProjectsRead,
    ProjectsWrite,
    AudioNativeRead,
    AudioNativeWrite,
    WorkspaceRead,
    WorkspaceWrite,
    ForcedAlignment,
    ConvaiRead,
    ConvaiWrite,
    MusicGeneration,
    ImageVideoGeneration,
    Flows,
    Templates,
    AddVoiceFromVoiceLibrary,
    CreateInstantVoiceClone,
    CreateProfessionalVoiceClone,
    PublishVoiceToVoiceLibrary,
    ShareVoiceExternally,
    CreateUserApiKey,
    WorkspaceAnalyticsFullRead,
    WebhooksWrite,
    ServiceAccountWrite,
    GroupMembersManage,
    WorkspaceMembersRead,
    WorkspaceMembersInvite,
    WorkspaceMembersRemove,
    TermsOfServiceAccept,
    AuditLogRead,
    ConversationPrivacyManage,
    CopyResourcesCrossWorkspace,
    SynthidDetector,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for PermissionType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::TextToSpeech => serializer.serialize_str("text_to_speech"),
            Self::SpeechToSpeech => serializer.serialize_str("speech_to_speech"),
            Self::SpeechToText => serializer.serialize_str("speech_to_text"),
            Self::ModelsRead => serializer.serialize_str("models_read"),
            Self::ModelsWrite => serializer.serialize_str("models_write"),
            Self::VoicesRead => serializer.serialize_str("voices_read"),
            Self::VoicesWrite => serializer.serialize_str("voices_write"),
            Self::SpeechHistoryRead => serializer.serialize_str("speech_history_read"),
            Self::SpeechHistoryWrite => serializer.serialize_str("speech_history_write"),
            Self::SoundGeneration => serializer.serialize_str("sound_generation"),
            Self::AudioIsolation => serializer.serialize_str("audio_isolation"),
            Self::VoiceGeneration => serializer.serialize_str("voice_generation"),
            Self::DubbingRead => serializer.serialize_str("dubbing_read"),
            Self::DubbingWrite => serializer.serialize_str("dubbing_write"),
            Self::PronunciationDictionariesRead => serializer.serialize_str("pronunciation_dictionaries_read"),
            Self::PronunciationDictionariesWrite => serializer.serialize_str("pronunciation_dictionaries_write"),
            Self::UserRead => serializer.serialize_str("user_read"),
            Self::UserWrite => serializer.serialize_str("user_write"),
            Self::ProjectsRead => serializer.serialize_str("projects_read"),
            Self::ProjectsWrite => serializer.serialize_str("projects_write"),
            Self::AudioNativeRead => serializer.serialize_str("audio_native_read"),
            Self::AudioNativeWrite => serializer.serialize_str("audio_native_write"),
            Self::WorkspaceRead => serializer.serialize_str("workspace_read"),
            Self::WorkspaceWrite => serializer.serialize_str("workspace_write"),
            Self::ForcedAlignment => serializer.serialize_str("forced_alignment"),
            Self::ConvaiRead => serializer.serialize_str("convai_read"),
            Self::ConvaiWrite => serializer.serialize_str("convai_write"),
            Self::MusicGeneration => serializer.serialize_str("music_generation"),
            Self::ImageVideoGeneration => serializer.serialize_str("image_video_generation"),
            Self::Flows => serializer.serialize_str("flows"),
            Self::Templates => serializer.serialize_str("templates"),
            Self::AddVoiceFromVoiceLibrary => serializer.serialize_str("add_voice_from_voice_library"),
            Self::CreateInstantVoiceClone => serializer.serialize_str("create_instant_voice_clone"),
            Self::CreateProfessionalVoiceClone => serializer.serialize_str("create_professional_voice_clone"),
            Self::PublishVoiceToVoiceLibrary => serializer.serialize_str("publish_voice_to_voice_library"),
            Self::ShareVoiceExternally => serializer.serialize_str("share_voice_externally"),
            Self::CreateUserApiKey => serializer.serialize_str("create_user_api_key"),
            Self::WorkspaceAnalyticsFullRead => serializer.serialize_str("workspace_analytics_full_read"),
            Self::WebhooksWrite => serializer.serialize_str("webhooks_write"),
            Self::ServiceAccountWrite => serializer.serialize_str("service_account_write"),
            Self::GroupMembersManage => serializer.serialize_str("group_members_manage"),
            Self::WorkspaceMembersRead => serializer.serialize_str("workspace_members_read"),
            Self::WorkspaceMembersInvite => serializer.serialize_str("workspace_members_invite"),
            Self::WorkspaceMembersRemove => serializer.serialize_str("workspace_members_remove"),
            Self::TermsOfServiceAccept => serializer.serialize_str("terms_of_service_accept"),
            Self::AuditLogRead => serializer.serialize_str("audit_log_read"),
            Self::ConversationPrivacyManage => serializer.serialize_str("conversation_privacy_manage"),
            Self::CopyResourcesCrossWorkspace => serializer.serialize_str("copy_resources_cross_workspace"),
            Self::SynthidDetector => serializer.serialize_str("synthid_detector"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for PermissionType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "text_to_speech" => Ok(Self::TextToSpeech),
            "speech_to_speech" => Ok(Self::SpeechToSpeech),
            "speech_to_text" => Ok(Self::SpeechToText),
            "models_read" => Ok(Self::ModelsRead),
            "models_write" => Ok(Self::ModelsWrite),
            "voices_read" => Ok(Self::VoicesRead),
            "voices_write" => Ok(Self::VoicesWrite),
            "speech_history_read" => Ok(Self::SpeechHistoryRead),
            "speech_history_write" => Ok(Self::SpeechHistoryWrite),
            "sound_generation" => Ok(Self::SoundGeneration),
            "audio_isolation" => Ok(Self::AudioIsolation),
            "voice_generation" => Ok(Self::VoiceGeneration),
            "dubbing_read" => Ok(Self::DubbingRead),
            "dubbing_write" => Ok(Self::DubbingWrite),
            "pronunciation_dictionaries_read" => Ok(Self::PronunciationDictionariesRead),
            "pronunciation_dictionaries_write" => Ok(Self::PronunciationDictionariesWrite),
            "user_read" => Ok(Self::UserRead),
            "user_write" => Ok(Self::UserWrite),
            "projects_read" => Ok(Self::ProjectsRead),
            "projects_write" => Ok(Self::ProjectsWrite),
            "audio_native_read" => Ok(Self::AudioNativeRead),
            "audio_native_write" => Ok(Self::AudioNativeWrite),
            "workspace_read" => Ok(Self::WorkspaceRead),
            "workspace_write" => Ok(Self::WorkspaceWrite),
            "forced_alignment" => Ok(Self::ForcedAlignment),
            "convai_read" => Ok(Self::ConvaiRead),
            "convai_write" => Ok(Self::ConvaiWrite),
            "music_generation" => Ok(Self::MusicGeneration),
            "image_video_generation" => Ok(Self::ImageVideoGeneration),
            "flows" => Ok(Self::Flows),
            "templates" => Ok(Self::Templates),
            "add_voice_from_voice_library" => Ok(Self::AddVoiceFromVoiceLibrary),
            "create_instant_voice_clone" => Ok(Self::CreateInstantVoiceClone),
            "create_professional_voice_clone" => Ok(Self::CreateProfessionalVoiceClone),
            "publish_voice_to_voice_library" => Ok(Self::PublishVoiceToVoiceLibrary),
            "share_voice_externally" => Ok(Self::ShareVoiceExternally),
            "create_user_api_key" => Ok(Self::CreateUserApiKey),
            "workspace_analytics_full_read" => Ok(Self::WorkspaceAnalyticsFullRead),
            "webhooks_write" => Ok(Self::WebhooksWrite),
            "service_account_write" => Ok(Self::ServiceAccountWrite),
            "group_members_manage" => Ok(Self::GroupMembersManage),
            "workspace_members_read" => Ok(Self::WorkspaceMembersRead),
            "workspace_members_invite" => Ok(Self::WorkspaceMembersInvite),
            "workspace_members_remove" => Ok(Self::WorkspaceMembersRemove),
            "terms_of_service_accept" => Ok(Self::TermsOfServiceAccept),
            "audit_log_read" => Ok(Self::AuditLogRead),
            "conversation_privacy_manage" => Ok(Self::ConversationPrivacyManage),
            "copy_resources_cross_workspace" => Ok(Self::CopyResourcesCrossWorkspace),
            "synthid_detector" => Ok(Self::SynthidDetector),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for PermissionType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TextToSpeech => write!(f, "text_to_speech"),
            Self::SpeechToSpeech => write!(f, "speech_to_speech"),
            Self::SpeechToText => write!(f, "speech_to_text"),
            Self::ModelsRead => write!(f, "models_read"),
            Self::ModelsWrite => write!(f, "models_write"),
            Self::VoicesRead => write!(f, "voices_read"),
            Self::VoicesWrite => write!(f, "voices_write"),
            Self::SpeechHistoryRead => write!(f, "speech_history_read"),
            Self::SpeechHistoryWrite => write!(f, "speech_history_write"),
            Self::SoundGeneration => write!(f, "sound_generation"),
            Self::AudioIsolation => write!(f, "audio_isolation"),
            Self::VoiceGeneration => write!(f, "voice_generation"),
            Self::DubbingRead => write!(f, "dubbing_read"),
            Self::DubbingWrite => write!(f, "dubbing_write"),
            Self::PronunciationDictionariesRead => write!(f, "pronunciation_dictionaries_read"),
            Self::PronunciationDictionariesWrite => write!(f, "pronunciation_dictionaries_write"),
            Self::UserRead => write!(f, "user_read"),
            Self::UserWrite => write!(f, "user_write"),
            Self::ProjectsRead => write!(f, "projects_read"),
            Self::ProjectsWrite => write!(f, "projects_write"),
            Self::AudioNativeRead => write!(f, "audio_native_read"),
            Self::AudioNativeWrite => write!(f, "audio_native_write"),
            Self::WorkspaceRead => write!(f, "workspace_read"),
            Self::WorkspaceWrite => write!(f, "workspace_write"),
            Self::ForcedAlignment => write!(f, "forced_alignment"),
            Self::ConvaiRead => write!(f, "convai_read"),
            Self::ConvaiWrite => write!(f, "convai_write"),
            Self::MusicGeneration => write!(f, "music_generation"),
            Self::ImageVideoGeneration => write!(f, "image_video_generation"),
            Self::Flows => write!(f, "flows"),
            Self::Templates => write!(f, "templates"),
            Self::AddVoiceFromVoiceLibrary => write!(f, "add_voice_from_voice_library"),
            Self::CreateInstantVoiceClone => write!(f, "create_instant_voice_clone"),
            Self::CreateProfessionalVoiceClone => write!(f, "create_professional_voice_clone"),
            Self::PublishVoiceToVoiceLibrary => write!(f, "publish_voice_to_voice_library"),
            Self::ShareVoiceExternally => write!(f, "share_voice_externally"),
            Self::CreateUserApiKey => write!(f, "create_user_api_key"),
            Self::WorkspaceAnalyticsFullRead => write!(f, "workspace_analytics_full_read"),
            Self::WebhooksWrite => write!(f, "webhooks_write"),
            Self::ServiceAccountWrite => write!(f, "service_account_write"),
            Self::GroupMembersManage => write!(f, "group_members_manage"),
            Self::WorkspaceMembersRead => write!(f, "workspace_members_read"),
            Self::WorkspaceMembersInvite => write!(f, "workspace_members_invite"),
            Self::WorkspaceMembersRemove => write!(f, "workspace_members_remove"),
            Self::TermsOfServiceAccept => write!(f, "terms_of_service_accept"),
            Self::AuditLogRead => write!(f, "audit_log_read"),
            Self::ConversationPrivacyManage => write!(f, "conversation_privacy_manage"),
            Self::CopyResourcesCrossWorkspace => write!(f, "copy_resources_cross_workspace"),
            Self::SynthidDetector => write!(f, "synthid_detector"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
