pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum WorkspaceGroupPermission {
    TextToSpeech,
    SpeechToSpeech,
    SpeechToText,
    VoiceLab,
    SoundEffects,
    Projects,
    VoiceoverStudio,
    Dubbing,
    AudioNative,
    ConversationalAi,
    ConversationalAiRead,
    VoiceIsolator,
    AiSpeechClassifier,
    SynthidDetector,
    AddVoiceFromVoiceLibrary,
    CreateInstantVoiceClone,
    CreateProfessionalVoiceClone,
    CreateUserApiKey,
    PublishStudioProject,
    Music,
    ImageVideoGeneration,
    Flows,
    Templates,
    ShareVoiceExternally,
    PublishVoiceToVoiceLibrary,
    ViewFiatBalance,
    WorkspaceAnalyticsFullRead,
    ServiceAccountsManage,
    WebhooksManage,
    GroupMembersManage,
    WorkspaceMembersInvite,
    WorkspaceMembersRemove,
    TermsOfServiceAccept,
    AuditLogRead,
    ConversationPrivacyManage,
    CopyResourcesCrossWorkspace,
    VoiceDesign,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for WorkspaceGroupPermission {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::TextToSpeech => serializer.serialize_str("text_to_speech"),
            Self::SpeechToSpeech => serializer.serialize_str("speech_to_speech"),
            Self::SpeechToText => serializer.serialize_str("speech_to_text"),
            Self::VoiceLab => serializer.serialize_str("voice_lab"),
            Self::SoundEffects => serializer.serialize_str("sound_effects"),
            Self::Projects => serializer.serialize_str("projects"),
            Self::VoiceoverStudio => serializer.serialize_str("voiceover_studio"),
            Self::Dubbing => serializer.serialize_str("dubbing"),
            Self::AudioNative => serializer.serialize_str("audio_native"),
            Self::ConversationalAi => serializer.serialize_str("conversational_ai"),
            Self::ConversationalAiRead => serializer.serialize_str("conversational_ai_read"),
            Self::VoiceIsolator => serializer.serialize_str("voice_isolator"),
            Self::AiSpeechClassifier => serializer.serialize_str("ai_speech_classifier"),
            Self::SynthidDetector => serializer.serialize_str("synthid_detector"),
            Self::AddVoiceFromVoiceLibrary => serializer.serialize_str("add_voice_from_voice_library"),
            Self::CreateInstantVoiceClone => serializer.serialize_str("create_instant_voice_clone"),
            Self::CreateProfessionalVoiceClone => serializer.serialize_str("create_professional_voice_clone"),
            Self::CreateUserApiKey => serializer.serialize_str("create_user_api_key"),
            Self::PublishStudioProject => serializer.serialize_str("publish_studio_project"),
            Self::Music => serializer.serialize_str("music"),
            Self::ImageVideoGeneration => serializer.serialize_str("image_video_generation"),
            Self::Flows => serializer.serialize_str("flows"),
            Self::Templates => serializer.serialize_str("templates"),
            Self::ShareVoiceExternally => serializer.serialize_str("share_voice_externally"),
            Self::PublishVoiceToVoiceLibrary => serializer.serialize_str("publish_voice_to_voice_library"),
            Self::ViewFiatBalance => serializer.serialize_str("view_fiat_balance"),
            Self::WorkspaceAnalyticsFullRead => serializer.serialize_str("workspace_analytics_full_read"),
            Self::ServiceAccountsManage => serializer.serialize_str("service_accounts_manage"),
            Self::WebhooksManage => serializer.serialize_str("webhooks_manage"),
            Self::GroupMembersManage => serializer.serialize_str("group_members_manage"),
            Self::WorkspaceMembersInvite => serializer.serialize_str("workspace_members_invite"),
            Self::WorkspaceMembersRemove => serializer.serialize_str("workspace_members_remove"),
            Self::TermsOfServiceAccept => serializer.serialize_str("terms_of_service_accept"),
            Self::AuditLogRead => serializer.serialize_str("audit_log_read"),
            Self::ConversationPrivacyManage => serializer.serialize_str("conversation_privacy_manage"),
            Self::CopyResourcesCrossWorkspace => serializer.serialize_str("copy_resources_cross_workspace"),
            Self::VoiceDesign => serializer.serialize_str("voice_design"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for WorkspaceGroupPermission {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "text_to_speech" => Ok(Self::TextToSpeech),
            "speech_to_speech" => Ok(Self::SpeechToSpeech),
            "speech_to_text" => Ok(Self::SpeechToText),
            "voice_lab" => Ok(Self::VoiceLab),
            "sound_effects" => Ok(Self::SoundEffects),
            "projects" => Ok(Self::Projects),
            "voiceover_studio" => Ok(Self::VoiceoverStudio),
            "dubbing" => Ok(Self::Dubbing),
            "audio_native" => Ok(Self::AudioNative),
            "conversational_ai" => Ok(Self::ConversationalAi),
            "conversational_ai_read" => Ok(Self::ConversationalAiRead),
            "voice_isolator" => Ok(Self::VoiceIsolator),
            "ai_speech_classifier" => Ok(Self::AiSpeechClassifier),
            "synthid_detector" => Ok(Self::SynthidDetector),
            "add_voice_from_voice_library" => Ok(Self::AddVoiceFromVoiceLibrary),
            "create_instant_voice_clone" => Ok(Self::CreateInstantVoiceClone),
            "create_professional_voice_clone" => Ok(Self::CreateProfessionalVoiceClone),
            "create_user_api_key" => Ok(Self::CreateUserApiKey),
            "publish_studio_project" => Ok(Self::PublishStudioProject),
            "music" => Ok(Self::Music),
            "image_video_generation" => Ok(Self::ImageVideoGeneration),
            "flows" => Ok(Self::Flows),
            "templates" => Ok(Self::Templates),
            "share_voice_externally" => Ok(Self::ShareVoiceExternally),
            "publish_voice_to_voice_library" => Ok(Self::PublishVoiceToVoiceLibrary),
            "view_fiat_balance" => Ok(Self::ViewFiatBalance),
            "workspace_analytics_full_read" => Ok(Self::WorkspaceAnalyticsFullRead),
            "service_accounts_manage" => Ok(Self::ServiceAccountsManage),
            "webhooks_manage" => Ok(Self::WebhooksManage),
            "group_members_manage" => Ok(Self::GroupMembersManage),
            "workspace_members_invite" => Ok(Self::WorkspaceMembersInvite),
            "workspace_members_remove" => Ok(Self::WorkspaceMembersRemove),
            "terms_of_service_accept" => Ok(Self::TermsOfServiceAccept),
            "audit_log_read" => Ok(Self::AuditLogRead),
            "conversation_privacy_manage" => Ok(Self::ConversationPrivacyManage),
            "copy_resources_cross_workspace" => Ok(Self::CopyResourcesCrossWorkspace),
            "voice_design" => Ok(Self::VoiceDesign),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for WorkspaceGroupPermission {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TextToSpeech => write!(f, "text_to_speech"),
            Self::SpeechToSpeech => write!(f, "speech_to_speech"),
            Self::SpeechToText => write!(f, "speech_to_text"),
            Self::VoiceLab => write!(f, "voice_lab"),
            Self::SoundEffects => write!(f, "sound_effects"),
            Self::Projects => write!(f, "projects"),
            Self::VoiceoverStudio => write!(f, "voiceover_studio"),
            Self::Dubbing => write!(f, "dubbing"),
            Self::AudioNative => write!(f, "audio_native"),
            Self::ConversationalAi => write!(f, "conversational_ai"),
            Self::ConversationalAiRead => write!(f, "conversational_ai_read"),
            Self::VoiceIsolator => write!(f, "voice_isolator"),
            Self::AiSpeechClassifier => write!(f, "ai_speech_classifier"),
            Self::SynthidDetector => write!(f, "synthid_detector"),
            Self::AddVoiceFromVoiceLibrary => write!(f, "add_voice_from_voice_library"),
            Self::CreateInstantVoiceClone => write!(f, "create_instant_voice_clone"),
            Self::CreateProfessionalVoiceClone => write!(f, "create_professional_voice_clone"),
            Self::CreateUserApiKey => write!(f, "create_user_api_key"),
            Self::PublishStudioProject => write!(f, "publish_studio_project"),
            Self::Music => write!(f, "music"),
            Self::ImageVideoGeneration => write!(f, "image_video_generation"),
            Self::Flows => write!(f, "flows"),
            Self::Templates => write!(f, "templates"),
            Self::ShareVoiceExternally => write!(f, "share_voice_externally"),
            Self::PublishVoiceToVoiceLibrary => write!(f, "publish_voice_to_voice_library"),
            Self::ViewFiatBalance => write!(f, "view_fiat_balance"),
            Self::WorkspaceAnalyticsFullRead => write!(f, "workspace_analytics_full_read"),
            Self::ServiceAccountsManage => write!(f, "service_accounts_manage"),
            Self::WebhooksManage => write!(f, "webhooks_manage"),
            Self::GroupMembersManage => write!(f, "group_members_manage"),
            Self::WorkspaceMembersInvite => write!(f, "workspace_members_invite"),
            Self::WorkspaceMembersRemove => write!(f, "workspace_members_remove"),
            Self::TermsOfServiceAccept => write!(f, "terms_of_service_accept"),
            Self::AuditLogRead => write!(f, "audit_log_read"),
            Self::ConversationPrivacyManage => write!(f, "conversation_privacy_manage"),
            Self::CopyResourcesCrossWorkspace => write!(f, "copy_resources_cross_workspace"),
            Self::VoiceDesign => write!(f, "voice_design"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
