pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

/// Resource types that can be shared in the workspace. The name always need to match the collection names
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum WorkspaceResourceType {
    Voice,
    VoiceCollection,
    PronunciationDictionary,
    Dubbing,
    Project,
    ConvaiAgents,
    ConvaiKnowledgeBaseDocuments,
    ConvaiTools,
    ConvaiSettings,
    ConvaiSecrets,
    WorkspaceAuthConnections,
    ConvaiPhoneNumbers,
    ConvaiMcpServers,
    ConvaiApiIntegrationConnections,
    ConvaiApiIntegrationTriggerConnections,
    ConvaiBatchCalls,
    ConvaiAgentResponseTests,
    ConvaiTestSuiteInvocations,
    ConvaiCrawlJobs,
    ConvaiCrawlTasks,
    ConvaiKbExternalSyncJobs,
    ConvaiWhatsappAccounts,
    ConvaiAgentVersions,
    ConvaiAgentBranches,
    ConvaiAgentVersionsDeployments,
    ConvaiMemoryEntries,
    ConvaiCoachingProposals,
    ConvaiTemplates,
    Dashboard,
    DashboardConfiguration,
    ConvaiAgentDrafts,
    ResourceLocators,
    Assets,
    ContentGenerations,
    ContentTemplates,
    Songs,
    TranscriptionTasks,
    Avatars,
    AvatarVideoGenerations,
    ResourceCollection,
    StudioProjects,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for WorkspaceResourceType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Voice => serializer.serialize_str("voice"),
            Self::VoiceCollection => serializer.serialize_str("voice_collection"),
            Self::PronunciationDictionary => serializer.serialize_str("pronunciation_dictionary"),
            Self::Dubbing => serializer.serialize_str("dubbing"),
            Self::Project => serializer.serialize_str("project"),
            Self::ConvaiAgents => serializer.serialize_str("convai_agents"),
            Self::ConvaiKnowledgeBaseDocuments => serializer.serialize_str("convai_knowledge_base_documents"),
            Self::ConvaiTools => serializer.serialize_str("convai_tools"),
            Self::ConvaiSettings => serializer.serialize_str("convai_settings"),
            Self::ConvaiSecrets => serializer.serialize_str("convai_secrets"),
            Self::WorkspaceAuthConnections => serializer.serialize_str("workspace_auth_connections"),
            Self::ConvaiPhoneNumbers => serializer.serialize_str("convai_phone_numbers"),
            Self::ConvaiMcpServers => serializer.serialize_str("convai_mcp_servers"),
            Self::ConvaiApiIntegrationConnections => serializer.serialize_str("convai_api_integration_connections"),
            Self::ConvaiApiIntegrationTriggerConnections => serializer.serialize_str("convai_api_integration_trigger_connections"),
            Self::ConvaiBatchCalls => serializer.serialize_str("convai_batch_calls"),
            Self::ConvaiAgentResponseTests => serializer.serialize_str("convai_agent_response_tests"),
            Self::ConvaiTestSuiteInvocations => serializer.serialize_str("convai_test_suite_invocations"),
            Self::ConvaiCrawlJobs => serializer.serialize_str("convai_crawl_jobs"),
            Self::ConvaiCrawlTasks => serializer.serialize_str("convai_crawl_tasks"),
            Self::ConvaiKbExternalSyncJobs => serializer.serialize_str("convai_kb_external_sync_jobs"),
            Self::ConvaiWhatsappAccounts => serializer.serialize_str("convai_whatsapp_accounts"),
            Self::ConvaiAgentVersions => serializer.serialize_str("convai_agent_versions"),
            Self::ConvaiAgentBranches => serializer.serialize_str("convai_agent_branches"),
            Self::ConvaiAgentVersionsDeployments => serializer.serialize_str("convai_agent_versions_deployments"),
            Self::ConvaiMemoryEntries => serializer.serialize_str("convai_memory_entries"),
            Self::ConvaiCoachingProposals => serializer.serialize_str("convai_coaching_proposals"),
            Self::ConvaiTemplates => serializer.serialize_str("convai_templates"),
            Self::Dashboard => serializer.serialize_str("dashboard"),
            Self::DashboardConfiguration => serializer.serialize_str("dashboard_configuration"),
            Self::ConvaiAgentDrafts => serializer.serialize_str("convai_agent_drafts"),
            Self::ResourceLocators => serializer.serialize_str("resource_locators"),
            Self::Assets => serializer.serialize_str("assets"),
            Self::ContentGenerations => serializer.serialize_str("content_generations"),
            Self::ContentTemplates => serializer.serialize_str("content_templates"),
            Self::Songs => serializer.serialize_str("songs"),
            Self::TranscriptionTasks => serializer.serialize_str("transcription_tasks"),
            Self::Avatars => serializer.serialize_str("avatars"),
            Self::AvatarVideoGenerations => serializer.serialize_str("avatar_video_generations"),
            Self::ResourceCollection => serializer.serialize_str("resource_collection"),
            Self::StudioProjects => serializer.serialize_str("studio_projects"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for WorkspaceResourceType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "voice" => Ok(Self::Voice),
            "voice_collection" => Ok(Self::VoiceCollection),
            "pronunciation_dictionary" => Ok(Self::PronunciationDictionary),
            "dubbing" => Ok(Self::Dubbing),
            "project" => Ok(Self::Project),
            "convai_agents" => Ok(Self::ConvaiAgents),
            "convai_knowledge_base_documents" => Ok(Self::ConvaiKnowledgeBaseDocuments),
            "convai_tools" => Ok(Self::ConvaiTools),
            "convai_settings" => Ok(Self::ConvaiSettings),
            "convai_secrets" => Ok(Self::ConvaiSecrets),
            "workspace_auth_connections" => Ok(Self::WorkspaceAuthConnections),
            "convai_phone_numbers" => Ok(Self::ConvaiPhoneNumbers),
            "convai_mcp_servers" => Ok(Self::ConvaiMcpServers),
            "convai_api_integration_connections" => Ok(Self::ConvaiApiIntegrationConnections),
            "convai_api_integration_trigger_connections" => Ok(Self::ConvaiApiIntegrationTriggerConnections),
            "convai_batch_calls" => Ok(Self::ConvaiBatchCalls),
            "convai_agent_response_tests" => Ok(Self::ConvaiAgentResponseTests),
            "convai_test_suite_invocations" => Ok(Self::ConvaiTestSuiteInvocations),
            "convai_crawl_jobs" => Ok(Self::ConvaiCrawlJobs),
            "convai_crawl_tasks" => Ok(Self::ConvaiCrawlTasks),
            "convai_kb_external_sync_jobs" => Ok(Self::ConvaiKbExternalSyncJobs),
            "convai_whatsapp_accounts" => Ok(Self::ConvaiWhatsappAccounts),
            "convai_agent_versions" => Ok(Self::ConvaiAgentVersions),
            "convai_agent_branches" => Ok(Self::ConvaiAgentBranches),
            "convai_agent_versions_deployments" => Ok(Self::ConvaiAgentVersionsDeployments),
            "convai_memory_entries" => Ok(Self::ConvaiMemoryEntries),
            "convai_coaching_proposals" => Ok(Self::ConvaiCoachingProposals),
            "convai_templates" => Ok(Self::ConvaiTemplates),
            "dashboard" => Ok(Self::Dashboard),
            "dashboard_configuration" => Ok(Self::DashboardConfiguration),
            "convai_agent_drafts" => Ok(Self::ConvaiAgentDrafts),
            "resource_locators" => Ok(Self::ResourceLocators),
            "assets" => Ok(Self::Assets),
            "content_generations" => Ok(Self::ContentGenerations),
            "content_templates" => Ok(Self::ContentTemplates),
            "songs" => Ok(Self::Songs),
            "transcription_tasks" => Ok(Self::TranscriptionTasks),
            "avatars" => Ok(Self::Avatars),
            "avatar_video_generations" => Ok(Self::AvatarVideoGenerations),
            "resource_collection" => Ok(Self::ResourceCollection),
            "studio_projects" => Ok(Self::StudioProjects),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for WorkspaceResourceType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Voice => write!(f, "voice"),
            Self::VoiceCollection => write!(f, "voice_collection"),
            Self::PronunciationDictionary => write!(f, "pronunciation_dictionary"),
            Self::Dubbing => write!(f, "dubbing"),
            Self::Project => write!(f, "project"),
            Self::ConvaiAgents => write!(f, "convai_agents"),
            Self::ConvaiKnowledgeBaseDocuments => write!(f, "convai_knowledge_base_documents"),
            Self::ConvaiTools => write!(f, "convai_tools"),
            Self::ConvaiSettings => write!(f, "convai_settings"),
            Self::ConvaiSecrets => write!(f, "convai_secrets"),
            Self::WorkspaceAuthConnections => write!(f, "workspace_auth_connections"),
            Self::ConvaiPhoneNumbers => write!(f, "convai_phone_numbers"),
            Self::ConvaiMcpServers => write!(f, "convai_mcp_servers"),
            Self::ConvaiApiIntegrationConnections => write!(f, "convai_api_integration_connections"),
            Self::ConvaiApiIntegrationTriggerConnections => write!(f, "convai_api_integration_trigger_connections"),
            Self::ConvaiBatchCalls => write!(f, "convai_batch_calls"),
            Self::ConvaiAgentResponseTests => write!(f, "convai_agent_response_tests"),
            Self::ConvaiTestSuiteInvocations => write!(f, "convai_test_suite_invocations"),
            Self::ConvaiCrawlJobs => write!(f, "convai_crawl_jobs"),
            Self::ConvaiCrawlTasks => write!(f, "convai_crawl_tasks"),
            Self::ConvaiKbExternalSyncJobs => write!(f, "convai_kb_external_sync_jobs"),
            Self::ConvaiWhatsappAccounts => write!(f, "convai_whatsapp_accounts"),
            Self::ConvaiAgentVersions => write!(f, "convai_agent_versions"),
            Self::ConvaiAgentBranches => write!(f, "convai_agent_branches"),
            Self::ConvaiAgentVersionsDeployments => write!(f, "convai_agent_versions_deployments"),
            Self::ConvaiMemoryEntries => write!(f, "convai_memory_entries"),
            Self::ConvaiCoachingProposals => write!(f, "convai_coaching_proposals"),
            Self::ConvaiTemplates => write!(f, "convai_templates"),
            Self::Dashboard => write!(f, "dashboard"),
            Self::DashboardConfiguration => write!(f, "dashboard_configuration"),
            Self::ConvaiAgentDrafts => write!(f, "convai_agent_drafts"),
            Self::ResourceLocators => write!(f, "resource_locators"),
            Self::Assets => write!(f, "assets"),
            Self::ContentGenerations => write!(f, "content_generations"),
            Self::ContentTemplates => write!(f, "content_templates"),
            Self::Songs => write!(f, "songs"),
            Self::TranscriptionTasks => write!(f, "transcription_tasks"),
            Self::Avatars => write!(f, "avatars"),
            Self::AvatarVideoGenerations => write!(f, "avatar_video_generations"),
            Self::ResourceCollection => write!(f, "resource_collection"),
            Self::StudioProjects => write!(f, "studio_projects"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
