//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl elevenlabs_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> elevenlabs_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    let config = elevenlabs_sdk::ClientConfig::default();
    let http_client = elevenlabs_sdk::HttpClient::with_executor(
        adapter as Arc<dyn elevenlabs_sdk::RequestExecutor>,
        config.clone(),
    );
    elevenlabs_sdk::api::ApiClient {
        config,
        history: elevenlabs_sdk::api::HistoryClient { http_client: http_client.clone() },
        text_to_sound_effects: elevenlabs_sdk::api::TextToSoundEffectsClient { http_client: http_client.clone() },
        audio_isolation: elevenlabs_sdk::api::AudioIsolationClient { http_client: http_client.clone() },
        samples: elevenlabs_sdk::api::SamplesClient { http_client: http_client.clone() },
        text_to_speech: elevenlabs_sdk::api::TextToSpeechClient { http_client: http_client.clone() },
        text_to_dialogue: elevenlabs_sdk::api::TextToDialogueClient { http_client: http_client.clone() },
        speech_to_speech: elevenlabs_sdk::api::SpeechToSpeechClient { http_client: http_client.clone() },
        text_to_voice: elevenlabs_sdk::api::TextToVoiceClient {
            http_client: http_client.clone(),
            preview: elevenlabs_sdk::api::resources::text_to_voice::PreviewClient { http_client: http_client.clone() },
        },
        user: elevenlabs_sdk::api::UserClient {
            http_client: http_client.clone(),
            subscription: elevenlabs_sdk::api::resources::user::SubscriptionClient { http_client: http_client.clone() },
        },
        voices: elevenlabs_sdk::api::VoicesClient {
            http_client: http_client.clone(),
            settings: elevenlabs_sdk::api::resources::voices::SettingsClient3 { http_client: http_client.clone() },
            ivc: elevenlabs_sdk::api::resources::voices::IvcClient { http_client: http_client.clone() },
            pvc: elevenlabs_sdk::api::resources::voices::PvcClient {
                http_client: http_client.clone(),
                samples: elevenlabs_sdk::api::resources::voices::pvc::SamplesClient2 {
                    http_client: http_client.clone(),
                    audio: elevenlabs_sdk::api::resources::voices::pvc::samples::AudioClient3 { http_client: http_client.clone() },
                    waveform: elevenlabs_sdk::api::resources::voices::pvc::samples::WaveformClient { http_client: http_client.clone() },
                    speakers: elevenlabs_sdk::api::resources::voices::pvc::samples::SpeakersClient {
                        http_client: http_client.clone(),
                        audio: elevenlabs_sdk::api::resources::voices::pvc::samples::speakers::AudioClient4 { http_client: http_client.clone() },
                    },
                },
                verification: elevenlabs_sdk::api::resources::voices::pvc::VerificationClient {
                    http_client: http_client.clone(),
                    captcha: elevenlabs_sdk::api::resources::voices::pvc::verification::CaptchaClient { http_client: http_client.clone() },
                },
            },
            samples: elevenlabs_sdk::api::resources::voices::SamplesClient3 {
                http_client: http_client.clone(),
                audio: elevenlabs_sdk::api::resources::voices::samples::AudioClient5 { http_client: http_client.clone() },
            },
        },
        studio: elevenlabs_sdk::api::StudioClient {
            http_client: http_client.clone(),
            projects: elevenlabs_sdk::api::resources::studio::ProjectsClient {
                http_client: http_client.clone(),
                pronunciation_dictionaries: elevenlabs_sdk::api::resources::studio::projects::PronunciationDictionariesClient2 { http_client: http_client.clone() },
                content: elevenlabs_sdk::api::resources::studio::projects::ContentClient { http_client: http_client.clone() },
                snapshots: elevenlabs_sdk::api::resources::studio::projects::SnapshotsClient { http_client: http_client.clone() },
                chapters: elevenlabs_sdk::api::resources::studio::projects::ChaptersClient {
                    http_client: http_client.clone(),
                    snapshots: elevenlabs_sdk::api::resources::studio::projects::chapters::SnapshotsClient2 { http_client: http_client.clone() },
                },
            },
        },
        music: elevenlabs_sdk::api::MusicClient {
            http_client: http_client.clone(),
            composition_plan: elevenlabs_sdk::api::resources::music::CompositionPlanClient { http_client: http_client.clone() },
        },
        dubbing: elevenlabs_sdk::api::DubbingClient {
            http_client: http_client.clone(),
            project: elevenlabs_sdk::api::resources::dubbing::ProjectClient {
                http_client: http_client.clone(),
                language: elevenlabs_sdk::api::resources::dubbing::project::LanguageClient {
                    http_client: http_client.clone(),
                    transcript: elevenlabs_sdk::api::resources::dubbing::project::language::TranscriptClient3 { http_client: http_client.clone() },
                },
                transcript: elevenlabs_sdk::api::resources::dubbing::project::TranscriptClient2 { http_client: http_client.clone() },
            },
            resource: elevenlabs_sdk::api::resources::dubbing::ResourceClient {
                http_client: http_client.clone(),
                language: elevenlabs_sdk::api::resources::dubbing::resource::LanguageClient2 { http_client: http_client.clone() },
                segment: elevenlabs_sdk::api::resources::dubbing::resource::SegmentClient { http_client: http_client.clone() },
                speaker: elevenlabs_sdk::api::resources::dubbing::resource::SpeakerClient {
                    http_client: http_client.clone(),
                    segment: elevenlabs_sdk::api::resources::dubbing::resource::speaker::SegmentClient2 { http_client: http_client.clone() },
                },
            },
            audio: elevenlabs_sdk::api::resources::dubbing::AudioClient2 { http_client: http_client.clone() },
            transcript: elevenlabs_sdk::api::resources::dubbing::TranscriptClient { http_client: http_client.clone() },
            transcripts: elevenlabs_sdk::api::resources::dubbing::TranscriptsClient { http_client: http_client.clone() },
        },
        models: elevenlabs_sdk::api::ModelsClient { http_client: http_client.clone() },
        audio_native: elevenlabs_sdk::api::AudioNativeClient { http_client: http_client.clone() },
        usage: elevenlabs_sdk::api::UsageClient { http_client: http_client.clone() },
        pronunciation_dictionaries: elevenlabs_sdk::api::PronunciationDictionariesClient {
            http_client: http_client.clone(),
            rules: elevenlabs_sdk::api::resources::pronunciation_dictionaries::RulesClient { http_client: http_client.clone() },
        },
        workspace: elevenlabs_sdk::api::WorkspaceClient {
            http_client: http_client.clone(),
            audit_logs: elevenlabs_sdk::api::resources::workspace::AuditLogsClient { http_client: http_client.clone() },
            auth_connections: elevenlabs_sdk::api::resources::workspace::AuthConnectionsClient { http_client: http_client.clone() },
            groups: elevenlabs_sdk::api::resources::workspace::GroupsClient {
                http_client: http_client.clone(),
                members: elevenlabs_sdk::api::resources::workspace::groups::MembersClient2 { http_client: http_client.clone() },
            },
            invites: elevenlabs_sdk::api::resources::workspace::InvitesClient { http_client: http_client.clone() },
            members: elevenlabs_sdk::api::resources::workspace::MembersClient { http_client: http_client.clone() },
            resources: elevenlabs_sdk::api::resources::workspace::ResourcesClient { http_client: http_client.clone() },
            usage: elevenlabs_sdk::api::resources::workspace::UsageClient2 { http_client: http_client.clone() },
            analytics: elevenlabs_sdk::api::resources::workspace::AnalyticsClient2 {
                http_client: http_client.clone(),
                requests: elevenlabs_sdk::api::resources::workspace::analytics::RequestsClient { http_client: http_client.clone() },
            },
        },
        service_accounts: elevenlabs_sdk::api::ServiceAccountsClient {
            http_client: http_client.clone(),
            api_keys: elevenlabs_sdk::api::resources::service_accounts::ApiKeysClient { http_client: http_client.clone() },
        },
        webhooks: elevenlabs_sdk::api::WebhooksClient { http_client: http_client.clone() },
        speech_to_text: elevenlabs_sdk::api::SpeechToTextClient {
            http_client: http_client.clone(),
            transcripts: elevenlabs_sdk::api::resources::speech_to_text::TranscriptsClient2 { http_client: http_client.clone() },
        },
        forced_alignment: elevenlabs_sdk::api::ForcedAlignmentClient { http_client: http_client.clone() },
        conversational_ai: elevenlabs_sdk::api::ConversationalAiClient {
            http_client: http_client.clone(),
            conversations: elevenlabs_sdk::api::resources::conversational_ai::ConversationsClient {
                http_client: http_client.clone(),
                audio: elevenlabs_sdk::api::resources::conversational_ai::conversations::AudioClient { http_client: http_client.clone() },
                feedback: elevenlabs_sdk::api::resources::conversational_ai::conversations::FeedbackClient { http_client: http_client.clone() },
                messages: elevenlabs_sdk::api::resources::conversational_ai::conversations::MessagesClient { http_client: http_client.clone() },
                tags: elevenlabs_sdk::api::resources::conversational_ai::conversations::TagsClient { http_client: http_client.clone() },
                files: elevenlabs_sdk::api::resources::conversational_ai::conversations::FilesClient { http_client: http_client.clone() },
                topics: elevenlabs_sdk::api::resources::conversational_ai::conversations::TopicsClient { http_client: http_client.clone() },
                analysis: elevenlabs_sdk::api::resources::conversational_ai::conversations::AnalysisClient { http_client: http_client.clone() },
            },
            twilio: elevenlabs_sdk::api::resources::conversational_ai::TwilioClient { http_client: http_client.clone() },
            exotel: elevenlabs_sdk::api::resources::conversational_ai::ExotelClient { http_client: http_client.clone() },
            whatsapp: elevenlabs_sdk::api::resources::conversational_ai::WhatsappClient { http_client: http_client.clone() },
            agents: elevenlabs_sdk::api::resources::conversational_ai::AgentsClient {
                http_client: http_client.clone(),
                summaries: elevenlabs_sdk::api::resources::conversational_ai::agents::SummariesClient { http_client: http_client.clone() },
                widget: elevenlabs_sdk::api::resources::conversational_ai::agents::WidgetClient {
                    http_client: http_client.clone(),
                    avatar: elevenlabs_sdk::api::resources::conversational_ai::agents::widget::AvatarClient { http_client: http_client.clone() },
                },
                link: elevenlabs_sdk::api::resources::conversational_ai::agents::LinkClient { http_client: http_client.clone() },
                knowledge_base: elevenlabs_sdk::api::resources::conversational_ai::agents::KnowledgeBaseClient2 { http_client: http_client.clone() },
                llm_usage: elevenlabs_sdk::api::resources::conversational_ai::agents::LlmUsageClient2 { http_client: http_client.clone() },
                branches: elevenlabs_sdk::api::resources::conversational_ai::agents::BranchesClient { http_client: http_client.clone() },
                versions: elevenlabs_sdk::api::resources::conversational_ai::agents::VersionsClient { http_client: http_client.clone() },
                deployments: elevenlabs_sdk::api::resources::conversational_ai::agents::DeploymentsClient { http_client: http_client.clone() },
                drafts: elevenlabs_sdk::api::resources::conversational_ai::agents::DraftsClient { http_client: http_client.clone() },
            },
            tests: elevenlabs_sdk::api::resources::conversational_ai::TestsClient {
                http_client: http_client.clone(),
                folders: elevenlabs_sdk::api::resources::conversational_ai::tests::FoldersClient { http_client: http_client.clone() },
                invocations: elevenlabs_sdk::api::resources::conversational_ai::tests::InvocationsClient { http_client: http_client.clone() },
            },
            users: elevenlabs_sdk::api::resources::conversational_ai::UsersClient { http_client: http_client.clone() },
            phone_numbers: elevenlabs_sdk::api::resources::conversational_ai::PhoneNumbersClient { http_client: http_client.clone() },
            llm_usage: elevenlabs_sdk::api::resources::conversational_ai::LlmUsageClient { http_client: http_client.clone() },
            llm: elevenlabs_sdk::api::resources::conversational_ai::LlmClient { http_client: http_client.clone() },
            knowledge_base: elevenlabs_sdk::api::resources::conversational_ai::KnowledgeBaseClient {
                http_client: http_client.clone(),
                documents: elevenlabs_sdk::api::resources::conversational_ai::knowledge_base::DocumentsClient {
                    http_client: http_client.clone(),
                    summaries: elevenlabs_sdk::api::resources::conversational_ai::knowledge_base::documents::SummariesClient2 { http_client: http_client.clone() },
                    chunk: elevenlabs_sdk::api::resources::conversational_ai::knowledge_base::documents::ChunkClient { http_client: http_client.clone() },
                    chunks: elevenlabs_sdk::api::resources::conversational_ai::knowledge_base::documents::ChunksClient { http_client: http_client.clone() },
                },
                document: elevenlabs_sdk::api::resources::conversational_ai::knowledge_base::DocumentClient { http_client: http_client.clone() },
            },
            tools: elevenlabs_sdk::api::resources::conversational_ai::ToolsClient {
                http_client: http_client.clone(),
                executions: elevenlabs_sdk::api::resources::conversational_ai::tools::ExecutionsClient { http_client: http_client.clone() },
            },
            settings: elevenlabs_sdk::api::resources::conversational_ai::SettingsClient { http_client: http_client.clone() },
            secrets: elevenlabs_sdk::api::resources::conversational_ai::SecretsClient { http_client: http_client.clone() },
            batch_calls: elevenlabs_sdk::api::resources::conversational_ai::BatchCallsClient { http_client: http_client.clone() },
            sip_trunk: elevenlabs_sdk::api::resources::conversational_ai::SipTrunkClient { http_client: http_client.clone() },
            mcp_servers: elevenlabs_sdk::api::resources::conversational_ai::McpServersClient {
                http_client: http_client.clone(),
                tools: elevenlabs_sdk::api::resources::conversational_ai::mcp_servers::ToolsClient2 { http_client: http_client.clone() },
                approval_policy: elevenlabs_sdk::api::resources::conversational_ai::mcp_servers::ApprovalPolicyClient { http_client: http_client.clone() },
                tool_approvals: elevenlabs_sdk::api::resources::conversational_ai::mcp_servers::ToolApprovalsClient { http_client: http_client.clone() },
                tool_configs: elevenlabs_sdk::api::resources::conversational_ai::mcp_servers::ToolConfigsClient { http_client: http_client.clone() },
            },
            whatsapp_accounts: elevenlabs_sdk::api::resources::conversational_ai::WhatsappAccountsClient { http_client: http_client.clone() },
            analytics: elevenlabs_sdk::api::resources::conversational_ai::AnalyticsClient {
                http_client: http_client.clone(),
                live_count: elevenlabs_sdk::api::resources::conversational_ai::analytics::LiveCountClient { http_client: http_client.clone() },
            },
            dashboard: elevenlabs_sdk::api::resources::conversational_ai::DashboardClient {
                http_client: http_client.clone(),
                settings: elevenlabs_sdk::api::resources::conversational_ai::dashboard::SettingsClient2 { http_client: http_client.clone() },
            },
        },
        speech_engine: elevenlabs_sdk::api::SpeechEngineClient { http_client: http_client.clone() },
        environment_variables: elevenlabs_sdk::api::EnvironmentVariablesClient { http_client: http_client.clone() },
        auth: elevenlabs_sdk::api::AuthClient { http_client: http_client.clone() },
        productions: elevenlabs_sdk::api::ProductionsClient {
            http_client: http_client.clone(),
            orders: elevenlabs_sdk::api::resources::productions::OrdersClient {
                http_client: http_client.clone(),
                media: elevenlabs_sdk::api::resources::productions::orders::MediaClient { http_client: http_client.clone() },
                items: elevenlabs_sdk::api::resources::productions::orders::ItemsClient { http_client: http_client.clone() },
                deliverables: elevenlabs_sdk::api::resources::productions::orders::DeliverablesClient { http_client: http_client.clone() },
                languages: elevenlabs_sdk::api::resources::productions::orders::LanguagesClient { http_client: http_client.clone() },
            },
        },
        tokens: elevenlabs_sdk::api::TokensClient {
            http_client: http_client.clone(),
            single_use: elevenlabs_sdk::api::resources::tokens::SingleUseClient { http_client: http_client.clone() },
        },
        workspaces: elevenlabs_sdk::api::WorkspacesClient {
            http_client: http_client.clone(),
            api_keys: elevenlabs_sdk::api::resources::workspaces::ApiKeysClient2 { http_client: http_client.clone() },
        },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, elevenlabs_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: elevenlabs_sdk::ApiError) -> CliError {
    match e {
        elevenlabs_sdk::ApiError::Http { status, message } => CliError::Api {
            code: status,
            message,
            reason: http_status_reason(status).to_string(),
        },
        elevenlabs_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        elevenlabs_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}

fn http_status_reason(status: u16) -> &'static str {
    match status {
        400 => "badRequest",
        401 => "unauthorized",
        403 => "forbidden",
        404 => "notFound",
        408 => "requestTimeout",
        409 => "conflict",
        429 => "tooManyRequests",
        500 => "internalServerError",
        502 => "badGateway",
        503 => "serviceUnavailable",
        504 => "gatewayTimeout",
        _ => "httpError",
    }
}
